using System.Text.Json;
using Microsoft.Data.Sqlite;

namespace GfMusicManager.Core.Generation;

/// <summary>
/// Result of validating the files that DFG will load from a generated package.
/// </summary>
public sealed record DfgMusicGenerationPackageValidationResult(
    bool IsSuccess,
    IReadOnlyList<string> Checks,
    IReadOnlyList<string> Errors)
{
    public int CheckCount => Checks.Count;

    public int ErrorCount => Errors.Count;

    public string Summary => IsSuccess
        ? $"OK ({CheckCount} checks)"
        : $"Failed ({ErrorCount} error(s), {CheckCount} checks)";
}

/// <summary>
/// Validates the DFG package generated by GF Music Manager without loading it
/// into Skyrim.  This is intentionally a file-level check: the package
/// manifest, imported Music Track JSON, and external Music Type patch rows
/// must agree before the common MOD output is committed.
/// </summary>
public sealed class DfgMusicGenerationPackageValidator
{
    public const string MetadataFileName = "gfmm-dfg-output.json";

    private const string PackageManifestFileName = "manifest.json";
    private const string PackageDatabaseFileName = "package.db";

    public DfgMusicGenerationPackageValidationResult Validate(
        DfgMusicGenerationOutputResult output,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(output);

        return Validate(
            output.PackageDirectory,
            output.MetadataPath,
            output.PackageDatabasePath,
            output.ImportPaths,
            output.MusicTrackCount,
            output.MusicTypeCount,
            output.ExternalMusicTypePatchCount,
            output.OfficialReferenceCount,
            output.UnsupportedAssignmentCount,
            cancellationToken);
    }

    public DfgMusicGenerationPackageValidationResult Validate(
        string packageDirectory,
        string? metadataPath = null,
        string? packageDatabasePath = null,
        IReadOnlyList<string>? expectedImportPaths = null,
        int? expectedMusicTrackCount = null,
        int? expectedMusicTypeCount = null,
        int? expectedExternalPatchCount = null,
        int? expectedOfficialReferenceCount = null,
        int? expectedUnsupportedAssignmentCount = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(packageDirectory);

        var checks = new List<string>();
        var errors = new List<string>();
        void Check(string message) => checks.Add(message);
        void Error(string message) => errors.Add(message);

        try
        {
            cancellationToken.ThrowIfCancellationRequested();
            var fullPackageDirectory = Path.GetFullPath(packageDirectory);
            if (!Directory.Exists(fullPackageDirectory))
            {
                Error($"DFGパッケージフォルダがありません：{fullPackageDirectory}");
                return CreateResult(checks, errors);
            }

            var manifestPath = Path.Combine(
                fullPackageDirectory,
                PackageManifestFileName);
            var databasePath = string.IsNullOrWhiteSpace(packageDatabasePath)
                ? Path.Combine(fullPackageDirectory, PackageDatabaseFileName)
                : Path.GetFullPath(packageDatabasePath);
            var importsDirectory = Path.Combine(fullPackageDirectory, "imports");

            using var packageManifest = ReadJsonFile(
                manifestPath,
                "DFG package manifest",
                Check,
                Error);
            if (packageManifest is not null)
            {
                ValidatePackageManifest(
                    packageManifest.RootElement,
                    databasePath,
                    Check,
                    Error);
            }

            var importFiles = Directory.Exists(importsDirectory)
                ? Directory.EnumerateFiles(
                        importsDirectory,
                        "*.json",
                        SearchOption.TopDirectoryOnly)
                    .ToArray()
                : Array.Empty<string>();
            var importTracks = Directory.Exists(importsDirectory)
                ? ValidateImports(
                    importsDirectory,
                    importFiles.Length > 0 ? expectedImportPaths : null,
                    Check,
                    Error,
                    cancellationToken)
                : new Dictionary<string, ImportedTrackInfo>(
                    StringComparer.OrdinalIgnoreCase);
            var databaseTracks = ValidateDatabaseForms(
                databasePath,
                Check,
                Error,
                cancellationToken);
            var tracks = importTracks;
            if (importTracks.Count == 0 && databaseTracks.Count > 0)
            {
                tracks = databaseTracks;
                Check(
                    $"DFG importsは取り込み済みのためpackage.db/formsを検証（{tracks.Count}件）");
            }
            else if (importTracks.Count > 0 && databaseTracks.Count > 0 &&
                     !importTracks.Keys.ToHashSet(StringComparer.OrdinalIgnoreCase)
                         .SetEquals(databaseTracks.Keys))
            {
                Error("DFG importsとpackage.db/formsのMusic Track一覧が一致しません。");
            }

            if (tracks.Count == 0 &&
                (expectedMusicTrackCount is null || expectedMusicTrackCount.Value > 0))
            {
                Error("DFG Music Trackのimportまたはpackage.db/formsが見つかりません。");
            }
            CompareCount(
                "DFG Music Track",
                tracks.Count,
                expectedMusicTrackCount,
                Check,
                Error);

            using var metadata = string.IsNullOrWhiteSpace(metadataPath)
                ? null
                : ReadJsonFile(
                    Path.GetFullPath(metadataPath),
                    "DFG output metadata",
                    Check,
                    Error);

            var metadataTrackIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var metadataTypeIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var metadataUnsupportedCount = 0;
            if (metadata is not null)
            {
                ValidateMetadata(
                    metadata.RootElement,
                    tracks,
                    metadataTrackIds,
                    metadataTypeIds,
                    ref metadataUnsupportedCount,
                    Check,
                    Error,
                    cancellationToken);
                CompareCount(
                    "DFG metadata Music Track",
                    metadataTrackIds.Count,
                    expectedMusicTrackCount,
                    Check,
                    Error);
                CompareCount(
                    "DFG metadata Music Type",
                    metadataTypeIds.Count,
                    expectedMusicTypeCount,
                    Check,
                    Error);
                CompareCount(
                    "DFG metadata unsupported assignment",
                    metadataUnsupportedCount,
                    expectedUnsupportedAssignmentCount,
                    Check,
                    Error);
            }
            else if (metadataPath is not null)
            {
                Error("DFG output metadataを検証できませんでした。");
            }

            var database = ValidateDatabase(
                databasePath,
                tracks.Keys,
                metadataTypeIds,
                Check,
                Error,
                cancellationToken);
            CompareCount(
                "DFG Music Type patch",
                database.PatchCount,
                expectedExternalPatchCount,
                Check,
                Error);
            CompareCount(
                "DFG official Music Track reference",
                database.OfficialReferenceCount,
                expectedOfficialReferenceCount,
                Check,
                Error);

            if (expectedMusicTypeCount is not null &&
                database.PatchCount != expectedMusicTypeCount.Value)
            {
                Error(
                    $"DFG Music Type数と外部パッチ数が一致しません：" +
                    $"Type {expectedMusicTypeCount.Value}件 / patch {database.PatchCount}件");
            }

            if (metadataTypeIds.Count > 0 &&
                !metadataTypeIds.SetEquals(database.PatchEditorIds))
            {
                Error("DFG metadataのMusic Type一覧とpackage.dbの外部パッチ一覧が一致しません。");
            }

            if (errors.Count == 0)
            {
                Check("DFG package manifest・Track JSON・package.dbの整合性が一致");
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception exception)
        {
            Error($"DFGパッケージの検証に失敗しました：{exception.Message}");
        }

        return CreateResult(checks, errors);
    }

    private static JsonDocument? ReadJsonFile(
        string path,
        string label,
        Action<string> check,
        Action<string> error)
    {
        if (!File.Exists(path))
        {
            error($"{label}がありません：{path}");
            return null;
        }

        try
        {
            var document = JsonDocument.Parse(File.ReadAllText(path));
            check($"{label}を読み込みました");
            return document;
        }
        catch (Exception exception)
        {
            error($"{label}を読み込めません：{exception.Message}");
            return null;
        }
    }

    private static void ValidatePackageManifest(
        JsonElement root,
        string databasePath,
        Action<string> check,
        Action<string> error)
    {
        if (!TryGetInt(root, "schemaVersion", out var schemaVersion) ||
            schemaVersion != 1)
        {
            error("DFG package manifestのschemaVersionが1ではありません。");
        }

        if (!TryGetNonEmptyString(root, "packageId") ||
            !TryGetNonEmptyString(root, "displayName") ||
            !TryGetNonEmptyString(root, "version"))
        {
            error("DFG package manifestの識別情報が不足しています。");
        }

        if (!TryGetString(root, "database", out var database) ||
            !database.Equals(PackageDatabaseFileName, StringComparison.OrdinalIgnoreCase))
        {
            error("DFG package manifestのdatabaseがpackage.dbを指していません。");
        }
        else if (File.Exists(databasePath))
        {
            check("DFG package manifestがpackage.dbを指しています");
        }

        if (!TryGetArray(root, "pluginDependencies", out _))
        {
            error("DFG package manifestにpluginDependenciesがありません。");
        }
    }

    private static Dictionary<string, ImportedTrackInfo> ValidateImports(
        string importsDirectory,
        IReadOnlyList<string>? expectedImportPaths,
        Action<string> check,
        Action<string> error,
        CancellationToken cancellationToken)
    {
        var result = new Dictionary<string, ImportedTrackInfo>(
            StringComparer.OrdinalIgnoreCase);
        if (!Directory.Exists(importsDirectory))
        {
            error($"DFG importsフォルダがありません：{importsDirectory}");
            return result;
        }

        var actualPaths = Directory.EnumerateFiles(
                importsDirectory,
                "*.json",
                SearchOption.TopDirectoryOnly)
            .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        if (expectedImportPaths is not null)
        {
            var expected = expectedImportPaths
                .Select(Path.GetFullPath)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);
            var actual = actualPaths
                .Select(Path.GetFullPath)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);
            if (!expected.SetEquals(actual))
            {
                error(
                    $"DFG Track JSONのファイル一覧が生成結果と一致しません：" +
                    $"予定 {expected.Count}件 / 実体 {actual.Count}件");
            }
            else
            {
                check($"DFG Track JSONのファイル一覧が一致（{actual.Count}件）");
            }
        }

        foreach (var path in actualPaths)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                using var document = JsonDocument.Parse(File.ReadAllText(path));
                var root = document.RootElement;
                if (!TryGetInt(root, "schemaVersion", out var schemaVersion) ||
                    schemaVersion != 1)
                {
                    error($"DFG Track JSONのschemaVersionが不正です：{path}");
                    continue;
                }

                if (!TryGetString(root, "formKind", out var formKind) ||
                    !formKind.Equals("MusicTrack", StringComparison.OrdinalIgnoreCase))
                {
                    error($"DFG importのformKindがMusicTrackではありません：{path}");
                    continue;
                }

                if (!TryGetString(root, "editorId", out var editorId) ||
                    string.IsNullOrWhiteSpace(editorId))
                {
                    error($"DFG Track JSONにeditorIdがありません：{path}");
                    continue;
                }

                if (!TryGetString(root, "musicTrackPath", out var audioPath) ||
                    string.IsNullOrWhiteSpace(audioPath))
                {
                    error($"DFG Track JSONに音源パスがありません：{path}");
                    continue;
                }

                if (!TryGetArray(root, "conditions", out var conditions))
                {
                    error($"DFG Track JSONにconditionsがありません：{path}");
                    continue;
                }

                foreach (var condition in conditions.EnumerateArray())
                {
                    if (!TryGetString(condition, "functionName", out _) ||
                        !TryGetInt(condition, "functionId", out _))
                    {
                        error($"DFG Track JSONの再生条件が不正です：{path}");
                        break;
                    }
                }

                if (!result.TryAdd(
                        editorId,
                        new ImportedTrackInfo(
                            Path.GetFullPath(path),
                            NormalizeVirtualPath(audioPath),
                            conditions.GetArrayLength())) )
                {
                    error($"DFG Track JSONのeditorIdが重複しています：{editorId}");
                    continue;
                }

                check($"DFG Music Track {editorId}を検証しました");
            }
            catch (Exception exception)
            {
                error($"DFG Track JSONを検証できません：{path} ({exception.Message})");
            }
        }

        return result;
    }

    private static Dictionary<string, ImportedTrackInfo> ValidateDatabaseForms(
        string databasePath,
        Action<string> check,
        Action<string> error,
        CancellationToken cancellationToken)
    {
        var result = new Dictionary<string, ImportedTrackInfo>(
            StringComparer.OrdinalIgnoreCase);
        if (!File.Exists(databasePath))
        {
            return result;
        }

        var connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = Path.GetFullPath(databasePath),
            Mode = SqliteOpenMode.ReadOnly,
            Cache = SqliteCacheMode.Private,
            Pooling = false
        }.ToString();

        try
        {
            using var connection = new SqliteConnection(connectionString);
            connection.Open();
            var tables = ReadTableNames(connection);
            if (!tables.Contains("forms"))
            {
                return result;
            }

            using var command = connection.CreateCommand();
            command.CommandText = """
                SELECT editor_id, form_kind, payload
                FROM forms
                ORDER BY editor_id;
                """;
            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                cancellationToken.ThrowIfCancellationRequested();
                var editorId = reader.GetString(0);
                var formKind = reader.GetString(1);
                var payload = reader.GetString(2);
                if (!formKind.Equals("MusicTrack", StringComparison.OrdinalIgnoreCase))
                {
                    error($"DFG package.db/formsにMusic Track以外のFormがあります：{editorId}");
                    continue;
                }

                try
                {
                    using var document = JsonDocument.Parse(payload);
                    var root = document.RootElement;
                    if (!TryGetInt(root, "schemaVersion", out var schemaVersion) ||
                        schemaVersion != 1 ||
                        !TryGetString(root, "editorId", out var payloadEditorId) ||
                        !payloadEditorId.Equals(editorId, StringComparison.OrdinalIgnoreCase) ||
                        !TryGetString(root, "formKind", out var payloadFormKind) ||
                        !payloadFormKind.Equals("MusicTrack", StringComparison.OrdinalIgnoreCase) ||
                        !TryGetString(root, "musicTrackPath", out var audioPath) ||
                        string.IsNullOrWhiteSpace(audioPath) ||
                        !TryGetArray(root, "conditions", out var conditions))
                    {
                        error($"DFG package.db/formsのMusic Track payloadが不正です：{editorId}");
                        continue;
                    }

                    if (!result.TryAdd(
                            editorId,
                            new ImportedTrackInfo(
                                Path.GetFullPath(databasePath),
                                NormalizeVirtualPath(audioPath),
                                conditions.GetArrayLength())))
                    {
                        error($"DFG package.db/formsのMusic Track識別子が重複しています：{editorId}");
                        continue;
                    }

                    check($"DFG package.db/formsのMusic Track {editorId}を検証しました");
                }
                catch (Exception exception)
                {
                    error($"DFG package.db/formsのMusic Track payloadを読み込めません：{editorId} ({exception.Message})");
                }
            }
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            error($"DFG package.db/formsを読み込めません：{exception.Message}");
        }

        return result;
    }

    private static void ValidateMetadata(
        JsonElement root,
        IReadOnlyDictionary<string, ImportedTrackInfo> tracks,
        ISet<string> metadataTrackIds,
        ISet<string> metadataTypeIds,
        ref int unsupportedAssignmentCount,
        Action<string> check,
        Action<string> error,
        CancellationToken cancellationToken)
    {
        if (!TryGetInt(root, "schemaVersion", out var schemaVersion) ||
            schemaVersion != 1)
        {
            error("DFG output metadataのschemaVersionが1ではありません。");
        }

        if (!TryGetString(root, "mode", out var mode) ||
            !mode.Equals(
                "dfg-music-track-import-and-music-type-external-patch",
                StringComparison.OrdinalIgnoreCase))
        {
            error("DFG output metadataのmodeが不正です。");
        }

        if (!TryGetArray(root, "musicTracks", out var musicTracks))
        {
            error("DFG output metadataにmusicTracksがありません。");
        }
        else
        {
            foreach (var track in musicTracks.EnumerateArray())
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (!TryGetString(track, "editorId", out var editorId) ||
                    string.IsNullOrWhiteSpace(editorId) ||
                    !metadataTrackIds.Add(editorId))
                {
                    error("DFG output metadataのMusic Track識別子が不正または重複しています。");
                    continue;
                }

                if (!tracks.TryGetValue(editorId, out var imported))
                {
                    error($"DFG metadataのMusic Trackがimportにありません：{editorId}");
                    continue;
                }

                if (!TryGetString(track, "audioPath", out var audioPath) ||
                    !NormalizeVirtualPath(audioPath).Equals(
                        imported.AudioPath,
                        StringComparison.OrdinalIgnoreCase))
                {
                    error($"DFG metadataの音源パスがimportと一致しません：{editorId}");
                }

                if (!TryGetInt(track, "conditionCount", out var conditionCount) ||
                    conditionCount != imported.ConditionCount)
                {
                    error($"DFG metadataの再生条件数がimportと一致しません：{editorId}");
                }
            }
        }

        if (!TryGetArray(root, "musicTypes", out var musicTypes))
        {
            error("DFG output metadataにmusicTypesがありません。");
        }
        else
        {
            foreach (var type in musicTypes.EnumerateArray())
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (!TryGetString(type, "editorId", out var editorId) ||
                    string.IsNullOrWhiteSpace(editorId) ||
                    !metadataTypeIds.Add(editorId))
                {
                    error("DFG output metadataのMusic Type識別子が不正または重複しています。");
                    continue;
                }

                if (!TryGetString(type, "output", out var output) ||
                    !output.Equals("external-patch", StringComparison.OrdinalIgnoreCase))
                {
                    error($"DFG metadataのMusic Type出力方式が不正です：{editorId}");
                }
            }
        }

        if (!TryGetArray(root, "unsupportedAssignments", out var unsupportedAssignments))
        {
            error("DFG output metadataにunsupportedAssignmentsがありません。");
        }
        else
        {
            unsupportedAssignmentCount = unsupportedAssignments.GetArrayLength();
        }

        if (!TryGetArray(root, "limitations", out _))
        {
            error("DFG output metadataにlimitationsがありません。");
        }

        check(
            $"DFG output metadataを検証しました（Track {metadataTrackIds.Count}件 / " +
            $"Type {metadataTypeIds.Count}件）");
    }

    private static DatabaseValidationSummary ValidateDatabase(
        string databasePath,
        IEnumerable<string> importedTrackIds,
        IReadOnlySet<string> metadataTypeIds,
        Action<string> check,
        Action<string> error,
        CancellationToken cancellationToken)
    {
        var summary = new DatabaseValidationSummary();
        if (!File.Exists(databasePath))
        {
            error($"DFG package.dbがありません：{databasePath}");
            return summary;
        }

        var imported = importedTrackIds.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = Path.GetFullPath(databasePath),
            Mode = SqliteOpenMode.ReadOnly,
            Cache = SqliteCacheMode.Private,
            Pooling = false
        }.ToString();

        try
        {
            using var connection = new SqliteConnection(connectionString);
            connection.Open();
            var tables = ReadTableNames(connection);
            foreach (var requiredTable in new[] { "forms", "patches", "external_patches" })
            {
                if (!tables.Contains(requiredTable))
                {
                    error($"DFG package.dbに{requiredTable}テーブルがありません。");
                }
            }

            if (!tables.Contains("external_patches"))
            {
                return summary;
            }

            using var command = connection.CreateCommand();
            command.CommandText = """
                SELECT source_plugin, local_form_id, form_kind,
                       editor_id, winning_plugin, changes_json
                FROM external_patches
                ORDER BY source_plugin, local_form_id, form_kind;
                """;
            using var reader = command.ExecuteReader();
            var identities = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            while (reader.Read())
            {
                cancellationToken.ThrowIfCancellationRequested();
                summary = summary with { PatchCount = summary.PatchCount + 1 };
                var sourcePlugin = reader.GetString(0);
                var localFormId = reader.GetInt64(1);
                var formKind = reader.GetString(2);
                var editorId = reader.GetString(3);
                var winningPlugin = reader.GetString(4);
                var changesJson = reader.GetString(5);
                var identity = $"{sourcePlugin}\u001f{localFormId:X}\u001f{formKind}";
                if (!identities.Add(identity))
                {
                    error($"DFG package.dbの外部パッチ識別子が重複しています：{identity}");
                }

                if (string.IsNullOrWhiteSpace(sourcePlugin) ||
                    localFormId <= 0 ||
                    !formKind.Equals("MusicType", StringComparison.OrdinalIgnoreCase) ||
                    string.IsNullOrWhiteSpace(editorId))
                {
                    error($"DFG package.dbのMusic Typeパッチ識別情報が不正です：{editorId}");
                    continue;
                }

                summary = summary with
                {
                    PatchEditorIds = summary.PatchEditorIds
                        .Append(editorId)
                        .ToHashSet(StringComparer.OrdinalIgnoreCase)
                };
                ValidatePatchChanges(
                    editorId,
                    changesJson,
                    imported,
                    ref summary,
                    check,
                    error);
                if (!string.IsNullOrWhiteSpace(winningPlugin))
                {
                    check($"DFG Music Type {editorId}の勝者プラグイン情報を保持しています");
                }
            }

            if (metadataTypeIds.Count > 0 &&
                !metadataTypeIds.SetEquals(summary.PatchEditorIds))
            {
                error("DFG metadataのMusic Type識別子とpackage.dbのeditor_idが一致しません。");
            }
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            error($"DFG package.dbを読み込めません：{exception.Message}");
        }

        return summary;
    }

    private static void ValidatePatchChanges(
        string editorId,
        string changesJson,
        IReadOnlySet<string> importedTrackIds,
        ref DatabaseValidationSummary summary,
        Action<string> check,
        Action<string> error)
    {
        try
        {
            using var document = JsonDocument.Parse(changesJson);
            var root = document.RootElement;
            if (!TryGetInt(root, "schemaVersion", out var schemaVersion) ||
                schemaVersion != 1 ||
                !root.TryGetProperty("fields", out var fields) ||
                !fields.TryGetProperty("musicTypeTracks", out var trackField) ||
                !TryGetString(trackField, "operation", out var operation) ||
                (operation is not "replace" and not "set") ||
                !TryGetArray(trackField, "value", out var values))
            {
                error($"DFG Music Type {editorId}のTrack差分が不正です。");
                return;
            }

            foreach (var value in values.EnumerateArray())
            {
                var hasEditorId = TryGetString(value, "editorID", out var referenceEditorId) &&
                    !string.IsNullOrWhiteSpace(referenceEditorId);
                var hasFormId = TryGetString(value, "formID", out var formId) &&
                    !string.IsNullOrWhiteSpace(formId);
                if (!hasEditorId && !hasFormId)
                {
                    error($"DFG Music Type {editorId}に空のTrack参照があります。");
                    continue;
                }

                if (hasFormId)
                {
                    if (!formId.Contains('|', StringComparison.Ordinal))
                    {
                        error($"DFG Music Type {editorId}の公式Track FormIDが不正です：{formId}");
                        continue;
                    }

                    summary = summary with
                    {
                        OfficialReferenceCount = summary.OfficialReferenceCount + 1
                    };
                }
                else if (!importedTrackIds.Contains(referenceEditorId))
                {
                    error(
                        $"DFG Music Type {editorId}が未生成のMusic Trackを参照しています：" +
                        referenceEditorId);
                }
            }

            check($"DFG Music Type {editorId}のTrack置換差分を検証しました");
        }
        catch (Exception exception)
        {
            error($"DFG Music Type {editorId}のTrack差分を読み込めません：{exception.Message}");
        }
    }

    private static HashSet<string> ReadTableNames(SqliteConnection connection)
    {
        using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT name
            FROM sqlite_master
            WHERE type = 'table';
            """;
        using var reader = command.ExecuteReader();
        var result = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        while (reader.Read())
        {
            result.Add(reader.GetString(0));
        }

        return result;
    }

    private static void CompareCount(
        string label,
        int actual,
        int? expected,
        Action<string> check,
        Action<string> error)
    {
        if (expected is null)
        {
            return;
        }

        if (actual == expected.Value)
        {
            check($"{label}数が一致（{actual}件）");
        }
        else
        {
            error($"{label}数が一致しません：予定 {expected.Value}件 / 実体 {actual}件");
        }
    }

    private static bool TryGetArray(
        JsonElement root,
        string propertyName,
        out JsonElement value) =>
        root.TryGetProperty(propertyName, out value) &&
        value.ValueKind == JsonValueKind.Array;

    private static bool TryGetInt(
        JsonElement root,
        string propertyName,
        out int value)
    {
        value = 0;
        return root.TryGetProperty(propertyName, out var property) &&
            property.ValueKind == JsonValueKind.Number &&
            property.TryGetInt32(out value);
    }

    private static bool TryGetString(
        JsonElement root,
        string propertyName,
        out string value)
    {
        value = string.Empty;
        if (!root.TryGetProperty(propertyName, out var property) ||
            property.ValueKind != JsonValueKind.String)
        {
            return false;
        }

        value = property.GetString() ?? string.Empty;
        return true;
    }

    private static bool TryGetNonEmptyString(
        JsonElement root,
        string propertyName) =>
        TryGetString(root, propertyName, out var value) &&
        !string.IsNullOrWhiteSpace(value);

    private static string NormalizeVirtualPath(string value) => value
        .Replace('\\', '/')
        .TrimStart('/');

    private static DfgMusicGenerationPackageValidationResult CreateResult(
        List<string> checks,
        List<string> errors) =>
        new(errors.Count == 0, checks.ToArray(), errors.ToArray());

    private sealed record ImportedTrackInfo(
        string Path,
        string AudioPath,
        int ConditionCount);

    private sealed record DatabaseValidationSummary
    {
        public int PatchCount { get; init; }

        public int OfficialReferenceCount { get; init; }

        public IReadOnlySet<string> PatchEditorIds { get; init; } =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase);
    }
}
