using System.Text;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;

namespace GfMusicManager.Core.Generation;

public sealed record GeneratedCellOutput(
    string CellFormKey,
    string? CellEditorId,
    string MusicTypeFormKey,
    string? MusicTypeEditorId);

internal static class MusicCellSkyPatcherOutput
{
    public const string RelativeFilePath =
        @"SKSE\Plugins\SkyPatcher\cell\GF Music Product\GF Music Product.esp.ini";

    public static string BuildIni(IReadOnlyList<GeneratedCellOutput> cells)
    {
        ArgumentNullException.ThrowIfNull(cells);

        var builder = new StringBuilder();
        builder.AppendLine("; Generated by GF Music Manager");
        builder.AppendLine("; Cell Music Type assignments are applied at runtime by SkyPatcher.");
        builder.AppendLine();
        foreach (var cell in cells.OrderBy(
                     cell => cell.CellFormKey,
                     StringComparer.OrdinalIgnoreCase))
        {
            builder.Append("filterByCells=")
                .Append(FormatFormKey(cell.CellFormKey, "Cell"))
                .Append(":musicType=")
                .AppendLine(FormatFormKey(cell.MusicTypeFormKey, "Music Type"));
        }

        return builder.ToString();
    }

    public static string FormatFormKey(string value, string label)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new MusicGenerationOutputException($"{label}のFormIDがありません。");
        }

        try
        {
            var formKey = FormKey.Factory(value);
            return $"{formKey.ModKey.FileName}|{formKey.ID:X6}";
        }
        catch
        {
            throw new MusicGenerationOutputException(
                $"{label}のFormIDをSkyPatcher形式へ変換できません：{value}");
        }
    }
}
