using SkyrimScan.Core.Scanning;
using Xunit;

namespace GfMusicManager.Core.Tests;

public sealed class Mo2ProfileStateWriterTests
{
    [Fact]
    public void Apply_UpdatesGeneratedModAndPluginAndDisablesSourcePlugin()
    {
        var root = Directory.CreateTempSubdirectory("gf-mo2-state-");
        try
        {
            var profilePath = Path.Combine(root.FullName, "profiles", "Main");
            Directory.CreateDirectory(profilePath);
            File.WriteAllLines(
                Path.Combine(profilePath, "modlist.txt"),
                new[] { "# This file was automatically generated by Mod Organizer.", "+Base Mod", "-Old Mod" });
            File.WriteAllLines(
                Path.Combine(profilePath, "loadorder.txt"),
                new[] { "Skyrim.esm", "Source.esp" });
            File.WriteAllLines(
                Path.Combine(profilePath, "plugins.txt"),
                new[] { "*Skyrim.esm", "*Source.esp" });

            var result = new Mo2ProfileStateWriter().Apply(
                root.FullName,
                "Main",
                "GF Music Product",
                new[] { "GF Music Product.esp" },
                enableGeneratedMod: true,
                new[] { "Source.esp" },
                disableSourcePlugins: true);

            Assert.True(result.Changed);
            var modList = File.ReadAllLines(Path.Combine(profilePath, "modlist.txt"));
            Assert.StartsWith("#", modList[0]);
            Assert.Equal("+GF Music Product", modList[1]);
            var snapshot = new Mo2ProfileReader().Read(root.FullName, "Main");
            Assert.Equal(2, snapshot.GetModPriority("GF Music Product"));
            var loadOrder = File.ReadAllLines(Path.Combine(profilePath, "loadorder.txt"));
            Assert.Equal("GF Music Product.esp", loadOrder[^1]);
            var plugins = File.ReadAllLines(Path.Combine(profilePath, "plugins.txt"));
            Assert.Contains("*GF Music Product.esp", plugins);
            Assert.Contains("Source.esp", plugins);
            Assert.DoesNotContain("*Source.esp", plugins);
        }
        finally
        {
            DeleteDirectory(root.FullName);
        }
    }

    [Fact]
    public void Apply_MovesExistingGeneratedModToHighestPriority()
    {
        var root = Directory.CreateTempSubdirectory("gf-mo2-state-reorder-");
        try
        {
            var profilePath = Path.Combine(root.FullName, "profiles", "Main");
            Directory.CreateDirectory(profilePath);
            File.WriteAllLines(
                Path.Combine(profilePath, "modlist.txt"),
                new[] { "+GF Music Product", "+Base Mod", "-GF Music Product", "+Last Mod" });
            File.WriteAllLines(
                Path.Combine(profilePath, "loadorder.txt"),
                new[]
                {
                    "GF Music Product - 02.esp",
                    "GF Music Product.esp",
                    "Skyrim.esm",
                    "GF Music Product.esp",
                    "Last.esp"
                });
            File.WriteAllLines(
                Path.Combine(profilePath, "plugins.txt"),
                new[]
                {
                    "*GF Music Product - 02.esp",
                    "*GF Music Product.esp",
                    "*Skyrim.esm",
                    "*Last.esp"
                });

            new Mo2ProfileStateWriter().Apply(
                root.FullName,
                "Main",
                "GF Music Product",
                new[] { "GF Music Product.esp" },
                enableGeneratedMod: true,
                Array.Empty<string>(),
                disableSourcePlugins: false);

            var modList = File.ReadAllLines(Path.Combine(profilePath, "modlist.txt"));
            Assert.Equal("+GF Music Product", modList[0]);
            Assert.Equal(1, modList.Count(line => line.Equals("+GF Music Product", StringComparison.Ordinal)));
            var snapshot = new Mo2ProfileReader().Read(root.FullName, "Main");
            Assert.Equal(2, snapshot.GetModPriority("GF Music Product"));

            var loadOrder = File.ReadAllLines(Path.Combine(profilePath, "loadorder.txt"));
            Assert.Equal("GF Music Product.esp", loadOrder[^1]);
            Assert.Equal(
                1,
                loadOrder.Count(line => line.Equals("GF Music Product.esp", StringComparison.OrdinalIgnoreCase)));
            Assert.DoesNotContain(
                "GF Music Product - 02.esp",
                loadOrder,
                StringComparer.OrdinalIgnoreCase);

            var plugins = File.ReadAllLines(Path.Combine(profilePath, "plugins.txt"));
            Assert.Contains("*GF Music Product.esp", plugins);
            Assert.DoesNotContain(
                "*GF Music Product - 02.esp",
                plugins,
                StringComparer.OrdinalIgnoreCase);
            Assert.Contains("*Last.esp", plugins);
        }
        finally
        {
            DeleteDirectory(root.FullName);
        }
    }

    [Fact]
    public void Apply_CanLeaveGeneratedModDisabled()
    {
        var root = Directory.CreateTempSubdirectory("gf-mo2-state-disabled-");
        try
        {
            var profilePath = Path.Combine(root.FullName, "profiles", "Main");
            Directory.CreateDirectory(profilePath);
            File.WriteAllText(Path.Combine(profilePath, "modlist.txt"), "+Base Mod\n");

            new Mo2ProfileStateWriter().Apply(
                root.FullName,
                "Main",
                "GF Music Product",
                new[] { "GF Music Product.esp" },
                enableGeneratedMod: false,
                Array.Empty<string>(),
                disableSourcePlugins: false);

            Assert.Contains("-GF Music Product", File.ReadAllLines(Path.Combine(profilePath, "modlist.txt")));
            Assert.Contains(
                "GF Music Product.esp",
                File.ReadAllLines(Path.Combine(profilePath, "plugins.txt")));
            Assert.DoesNotContain(
                "*GF Music Product.esp",
                File.ReadAllLines(Path.Combine(profilePath, "plugins.txt")));
        }
        finally
        {
            DeleteDirectory(root.FullName);
        }
    }

    [Fact]
    public void Apply_RemovesOldGeneratedPluginsWhenCurrentOutputHasNoPlugin()
    {
        var root = Directory.CreateTempSubdirectory("gf-mo2-state-dfg-");
        try
        {
            var profilePath = Path.Combine(root.FullName, "profiles", "Main");
            Directory.CreateDirectory(profilePath);
            File.WriteAllLines(
                Path.Combine(profilePath, "modlist.txt"),
                new[] { "+Base Mod", "+GF Music Product" });
            File.WriteAllLines(
                Path.Combine(profilePath, "loadorder.txt"),
                new[] { "Skyrim.esm", "GF Music Product.esp", "GF Music Product - 02.esp" });
            File.WriteAllLines(
                Path.Combine(profilePath, "plugins.txt"),
                new[] { "*Skyrim.esm", "*GF Music Product.esp", "GF Music Product - 02.esp" });

            new Mo2ProfileStateWriter().Apply(
                root.FullName,
                "Main",
                "GF Music Product",
                Array.Empty<string>(),
                enableGeneratedMod: true,
                Array.Empty<string>(),
                disableSourcePlugins: false);

            Assert.DoesNotContain(
                File.ReadAllLines(Path.Combine(profilePath, "loadorder.txt")),
                line => line.Contains("GF Music Product", StringComparison.OrdinalIgnoreCase));
            Assert.DoesNotContain(
                File.ReadAllLines(Path.Combine(profilePath, "plugins.txt")),
                line => line.Contains("GF Music Product", StringComparison.OrdinalIgnoreCase));
            Assert.Contains("*Skyrim.esm", File.ReadAllLines(Path.Combine(profilePath, "plugins.txt")));
        }
        finally
        {
            DeleteDirectory(root.FullName);
        }
    }

    private static void DeleteDirectory(string path)
    {
        if (Directory.Exists(path))
        {
            Directory.Delete(path, recursive: true);
        }
    }
}
